# Projectwork 3 : Analysis(Key Performance Indicator KPIs, Efficient Visualization, Measurement and dimenstions)

## **import Libraries**

**import all relevant library**

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import csv
import mysql.connector
import os

## **Import Incident Response Dataset**

In [2]:
#change directory
os.getcwd()
os.chdir('c:\\Users\\Sumit\\Documents\\Work_Drive\\edureka\\Python_edureka\\incidents_KPI\\')
os.getcwd()

'c:\\Users\\Sumit\\Documents\\Work_Drive\\edureka\\Python_edureka\\incidents_KPI'

In [3]:
#import csv Data
data=pd.read_csv('incident_event_log.csv')
data

,number,incident_state,active,reassignment_count,reopen_count,sys_mod_count,made_sla,caller_id,opened_by,opened_at,...,u_priority_confirmation,notify,problem_id,rfc,vendor,caused_by,closed_code,resolved_by,resolved_at,closed_at
0,INC0000045,New,True,0,0,0,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
1,INC0000045,Resolved,True,0,0,2,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
2,INC0000045,Resolved,True,0,0,3,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
3,INC0000045,Closed,False,0,0,4,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
4,INC0000047,New,True,0,0,0,True,Caller 2403,Opened by 397,29/2/2016 04:40,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 81,1/3/2016 09:52,6/3/2016 10:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119993,INC0029231,Resolved,True,0,0,8,True,Caller 2321,Opened by 17,13/5/2016 11:46,...,True,Do Not Notify,?,?,?,?,code 7,Resolved by 11,13/5/2016 12:15,18/5/2016 13:07
119994,INC0029231,Closed,False,0,0,9,True,Caller 2321,Opened by 17,13/5/2016 11:46,...,True,Do Not Notify,?,?,?,?,code 7,Resolved by 11,13/5/2016 12:15,18/5/2016 13:07
119995,INC0029232,Resolved,True,0,0,0,True,Caller 382,Opened by 108,13/5/2016 11:48,...,False,Do Not Notify,?,?,?,?,code 6,Resolved by 52,?,18/5/2016 12:07
119996,INC0029232,Closed,False,0,0,1,True,Caller 382,Opened by 108,13/5/2016 11:48,...,False,Do Not Notify,?,?,?,?,code 6,Resolved by 52,?,18/5/2016 12:07
119997,INC0029233,New,True,0,0,0,True,Caller 3033,Opened by 17,13/5/2016 11:49,...,False,Do Not Notify,?,?,?,?,code 6,Resolved by 180,17/5/2016 16:46,22/5/2016 17:07

## **Clean Data**

In [4]:
# Check for any column with empty values
data.caused_by.value_counts()
data

,number,incident_state,active,reassignment_count,reopen_count,sys_mod_count,made_sla,caller_id,opened_by,opened_at,...,u_priority_confirmation,notify,problem_id,rfc,vendor,caused_by,closed_code,resolved_by,resolved_at,closed_at
0,INC0000045,New,True,0,0,0,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
1,INC0000045,Resolved,True,0,0,2,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
2,INC0000045,Resolved,True,0,0,3,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
3,INC0000045,Closed,False,0,0,4,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
4,INC0000047,New,True,0,0,0,True,Caller 2403,Opened by 397,29/2/2016 04:40,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 81,1/3/2016 09:52,6/3/2016 10:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119993,INC0029231,Resolved,True,0,0,8,True,Caller 2321,Opened by 17,13/5/2016 11:46,...,True,Do Not Notify,?,?,?,?,code 7,Resolved by 11,13/5/2016 12:15,18/5/2016 13:07
119994,INC0029231,Closed,False,0,0,9,True,Caller 2321,Opened by 17,13/5/2016 11:46,...,True,Do Not Notify,?,?,?,?,code 7,Resolved by 11,13/5/2016 12:15,18/5/2016 13:07
119995,INC0029232,Resolved,True,0,0,0,True,Caller 382,Opened by 108,13/5/2016 11:48,...,False,Do Not Notify,?,?,?,?,code 6,Resolved by 52,?,18/5/2016 12:07
119996,INC0029232,Closed,False,0,0,1,True,Caller 382,Opened by 108,13/5/2016 11:48,...,False,Do Not Notify,?,?,?,?,code 6,Resolved by 52,?,18/5/2016 12:07
119997,INC0029233,New,True,0,0,0,True,Caller 3033,Opened by 17,13/5/2016 11:49,...,False,Do Not Notify,?,?,?,?,code 6,Resolved by 180,17/5/2016 16:46,22/5/2016 17:07

In [5]:
data.replace('?','Unknown' , inplace=True)
data.drop(columns=['active','rfc','closed_code','vendor','sys_created_at','closed_at','u_priority_confirmation','cmdb_ci','sys_updated_by','sys_updated_at','sys_created_by','problem_id','caused_by','sys_mod_count','notify'], inplace=True)
data.drop_duplicates()
data

,number,incident_state,reassignment_count,reopen_count,made_sla,caller_id,opened_by,opened_at,contact_type,location,...,subcategory,u_symptom,impact,urgency,priority,assignment_group,assigned_to,knowledge,resolved_by,resolved_at
0,INC0000045,New,0,0,True,Caller 2403,Opened by 8,29/2/2016 01:16,Phone,Location 143,...,Subcategory 170,Symptom 72,2 - Medium,2 - Medium,3 - Moderate,Group 56,Unknown,True,Resolved by 149,29/2/2016 11:29
1,INC0000045,Resolved,0,0,True,Caller 2403,Opened by 8,29/2/2016 01:16,Phone,Location 143,...,Subcategory 170,Symptom 72,2 - Medium,2 - Medium,3 - Moderate,Group 56,Unknown,True,Resolved by 149,29/2/2016 11:29
2,INC0000045,Resolved,0,0,True,Caller 2403,Opened by 8,29/2/2016 01:16,Phone,Location 143,...,Subcategory 170,Symptom 72,2 - Medium,2 - Medium,3 - Moderate,Group 56,Unknown,True,Resolved by 149,29/2/2016 11:29
3,INC0000045,Closed,0,0,True,Caller 2403,Opened by 8,29/2/2016 01:16,Phone,Location 143,...,Subcategory 170,Symptom 72,2 - Medium,2 - Medium,3 - Moderate,Group 56,Unknown,True,Resolved by 149,29/2/2016 11:29
4,INC0000047,New,0,0,True,Caller 2403,Opened by 397,29/2/2016 04:40,Phone,Location 165,...,Subcategory 215,Symptom 471,2 - Medium,2 - Medium,3 - Moderate,Group 70,Resolver 89,True,Resolved by 81,1/3/2016 09:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119993,INC0029231,Resolved,0,0,True,Caller 2321,Opened by 17,13/5/2016 11:46,Phone,Location 111,...,Subcategory 9,Unknown,2 - Medium,2 - Medium,3 - Moderate,Group 70,Resolver 13,False,Resolved by 11,13/5/2016 12:15
119994,INC0029231,Closed,0,0,True,Caller 2321,Opened by 17,13/5/2016 11:46,Phone,Location 111,...,Subcategory 9,Unknown,2 - Medium,2 - Medium,3 - Moderate,Group 70,Resolver 13,False,Resolved by 11,13/5/2016 12:15
119995,INC0029232,Resolved,0,0,True,Caller 382,Opened by 108,13/5/2016 11:48,Phone,Location 143,...,Subcategory 174,Unknown,2 - Medium,2 - Medium,3 - Moderate,Group 70,Resolver 56,False,Resolved by 52,Unknown
119996,INC0029232,Closed,0,0,True,Caller 382,Opened by 108,13/5/2016 11:48,Phone,Location 143,...,Subcategory 174,Unknown,2 - Medium,2 - Medium,3 - Moderate,Group 70,Resolver 56,False,Resolved by 52,Unknown
119997,INC0029233,New,0,0,True,Caller 3033,Opened by 17,13/5/2016 11:49,Phone,Location 97,...,Subcategory 36,Symptom 491,2 - Medium,2 - Medium,3 - Moderate,Group 73,Unknown,False,Resolved by 180,17/5/2016 16:46

# **Export to CSV**

In [6]:
# Export the modified DataFrame to a CSV file
data.to_csv('IT_Incident_Data.csv', index=False)

## **Import CSV Data to SQL Database instance**

**1.    Create new Database Instance 'mydbinstance Database TicketDatabase**

*import library*

In [7]:
import mysql.connector
import csv
import os

*creating new Database Instance 'mydbinstance'*

In [47]:
mydbinstance=mysql.connector.connect(
    host="localhost", #hostname
    user="root",
    password="Sumit@123",
    )

# proof of db connection
print(mydbinstance)

<mysql.connector.connection_cext.CMySQLConnection object at 0x000002D0D562EF60>

**2.    Create new Database 'TicketDatabase'**

*create database*

In [48]:

mycursor = mydbinstance.cursor()

In [ ]:
mycursor.execute("CREATE DATABASE TicketDatabase")

*Show database exist*

In [49]:

mycursor.execute("SHOW DATABASES")
for x in mycursor:
    print(x)

mycursor.close()

('information_schema',)
('mydatabase',)
('mysql',)
('performance_schema',)
('pyproject_database',)
('sys',)
('ticketdatabase',)

True

**3. Create 'IncidentMaster Table'**

*Add database name in instance*

In [50]:
mydbinstance=mysql.connector.connect(
    host="localhost", #hostname
    user="root",
    password="Sumit@123",
    database="ticketdatabase",
    allow_local_infile=True
    )

*open connection*

In [51]:
mycursor = mydbinstance.cursor()

*create IncidentMaster Table*

In [13]:
mycursor.execute("CREATE TABLE IF NOT EXISTS IncidentMaster (number VARCHAR(20),incident_state VARCHAR(50),reassignment_count INT,reopen_count INT,made_sla BOOLEAN,caller_id VARCHAR(50),opened_by VARCHAR(50),opened_at DATETIME,contact_type VARCHAR(50),location VARCHAR(100),category VARCHAR(100),subcategory VARCHAR(100),u_symptom VARCHAR(100),impact VARCHAR(50),urgency VARCHAR(50),priority VARCHAR(50),assignment_group VARCHAR(100),assigned_to VARCHAR(100),knowledge BOOLEAN,resolved_by VARCHAR(100),resolved_at DATETIME)")

ProgrammingError: 1046 (3D000): No database selected

*Show Table*

In [52]:
mycursor.execute("SHOW TABLES")
for x in mycursor:
    print(x)

('incidentmaster',)

*Show Table columns*

In [53]:
#mycursor.execute(" DESCRIBE incidentmaster;")
mycursor.execute(" SHOW COLUMNS from incidentmaster;")
for x in mycursor:
    print(x)

('number', 'varchar(20)', 'YES', '', None, '')
('incident_state', 'varchar(50)', 'YES', '', None, '')
('reassignment_count', 'int', 'YES', '', None, '')
('reopen_count', 'int', 'YES', '', None, '')
('made_sla', 'tinyint(1)', 'YES', '', None, '')
('caller_id', 'varchar(50)', 'YES', '', None, '')
('opened_by', 'varchar(50)', 'YES', '', None, '')
('opened_at', 'datetime', 'YES', '', None, '')
('contact_type', 'varchar(50)', 'YES', '', None, '')
('location', 'varchar(100)', 'YES', '', None, '')
('category', 'varchar(100)', 'YES', '', None, '')
('subcategory', 'varchar(100)', 'YES', '', None, '')
('u_symptom', 'varchar(100)', 'YES', '', None, '')
('impact', 'varchar(50)', 'YES', '', None, '')
('urgency', 'varchar(50)', 'YES', '', None, '')
('priority', 'varchar(50)', 'YES', '', None, '')
('assignment_group', 'varchar(100)', 'YES', '', None, '')
('assigned_to', 'varchar(100)', 'YES', '', None, '')
('knowledge', 'tinyint(1)', 'YES', '', None, '')
('resolved_by', 'varchar(100)', 'YES', '', None, '')
('resolved_at', 'datetime', 'YES', '', None, '')

In [58]:
mycursor.execute("SELECT * FROM incidentmaster WHERE number='INC0000045'")
result=mycursor.fetchall()
print(result)
for x in result:
    print(x)

[]

In [55]:
# Corrected load data query with proper quoting
load_data_query = f"""LOAD DATA LOCAL INFILE 'IT_Incident_Data.csv' INTO TABLE incidentmaster FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\\n' IGNORE 1 LINES;"""

In [56]:
load_data_query

'LOAD DATA LOCAL INFILE \'IT_Incident_Data.csv\' INTO TABLE incidentmaster FIELDS TERMINATED BY \',\' ENCLOSED BY \'"\' LINES TERMINATED BY \'\\n\' IGNORE 1 LINES;'

In [57]:


# Define the database name
database = "ticketdatabase"
host="localhost"
user="root"
password="Sumit@123"




# Run the data import command
os.system(f'mysql -h {host} -u {user} -p{password} --local-infile=1 -e "USE {database}; {load_data_query}"')

1

**SLA Table**

**IncidentResolution Table**

**IncidentPrioirty Table**

**IncidentStatus Table**

## **Analyse**

## **Visual Data with KPI**

## **Rough Notes**

In [144]:
df = pd.read_csv('IT_Incident_Data.csv')
df.columns

Index(['number', 'incident_state', 'reassignment_count', 'reopen_count',
       'made_sla', 'caller_id', 'opened_by', 'opened_at', 'contact_type',
       'location', 'category', 'subcategory', 'u_symptom', 'impact', 'urgency',
       'priority', 'assignment_group', 'assigned_to', 'knowledge',
       'resolved_by', 'resolved_at'],
      dtype='object')